# Generated by Django 5.2.3 on 2025-06-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reaction_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
