# Generated by Django 5.2.3 on 2025-06-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_reaction_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='description',
        ),
    ]
