# Generated by Django 5.2.3 on 2025-06-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_text_blog_description'),
        ('user', '0010_rename_surname_user_sur_name_remove_user_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
