# Generated by Django 5.2.3 on 2025-06-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_autor_alter_blog_title'),
        ('user', '0010_rename_surname_user_sur_name_remove_user_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Autor'),
        ),
    ]
