# Generated by Django 5.2.3 on 2025-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
