# Generated by Django 5.2.3 on 2025-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('userName', models.CharField(max_length=255, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('age', models.DateField(max_length=255, verbose_name='Data Nascimento')),
            ],
        ),
    ]
