# Generated by Django 5.2.3 on 2025-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Nome'),
        ),
    ]
