# Generated by Django 5.2.3 on 2025-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Usuário'),
        ),
    ]
