# Generated by Django 5.2.3 on 2025-06-26 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_options_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Espaços não são permitidos.', regex='^\\S+$')], verbose_name='Usuário'),
        ),
    ]
