# Generated by Django 5.2.3 on 2025-06-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('user', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='blog_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Publicações'),
        ),
    ]
