# Generated by Django 5.2.3 on 2025-06-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('user', '0008_rename_username_user_user_name_user_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Publicações'),
        ),
    ]
