# Generated by Django 5.2.3 on 2025-06-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surName',
            new_name='sur_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blog_post',
        ),
    ]
